version: '2.2'

services:
  postgres:
    build:
      dockerfile: Dockerfile.postgres
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'postgres'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/create_tables.sql

  file-service:
    build:
      dockerfile: Dockerfile.service
    image: 'file-service-app:latest'
    ports:
      - '8081:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'root'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
      JWT_SECRET_ACCESS: 'qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=='
      FILE_UPLOAD: './upload'

volumes:
  db:
    driver: local
